### ISSUE TITLE
plugin doesn't create MySQL-Tables

### ISSUE THREAD

**Issue by dedel1337** [txinto/redmine_wiki_books#10]
Hi,

I'm running Redmine 2.6.0 on a CentOS 6 system.
I copied the files in the plugin-folder and ran the command "rake redmine:plugins:migrate RAILS_ENV=production" without any errors.

the needed tables in the mysql-DB are not created by the script.
So I tried to execute the files in /db/migrate via ruby 001_create_books.rb.

This wasn't successful, so I added 

require 'active_record'
ActiveRecord::Base.establish_connection(
  :adapter  => "mysql",
  :host     => "localhost",
  :username => "XXXX",
  :password => "XXXX",
  :database => "redmine_db"
)

The script could be executed without any errors, but still no tables in mysql-DB.

Is there a bug? How should this system create the required MySQL-Tables`?

**Comment by txinto** [comment]
Hi, I have tested it on Redmine 2.5.2 and 2.4 with no issues.  Normally the tables are created by the Redmine.  

Plugins just define the migrations and the redmine plugin system does the work.  

Have you tried to install another plugin after this problem appeared?  

If the problem is in the redmine, the error will prevent other plugins tables to be created, so we can conclude if the plugin is inside the plugin or it is a case of the redmine installation.

Best regards.

**Comment by dedel1337** [comment]
Hi and thanks for your answer,

Just now I have installed a plugin called "issue_id" without any problems. 
The needed tables in the databases were created:

[root@redmine plugins]# rake redmine:plugins:migrate RAILS_ENV=production
(in /var/www/redmine)
Migrating issue_id (ISSUE-id)...
==  AddIssuesProjectKeyAndNumber: migrating ===================================
-- add_column(:issues, :project_key, :string, {:limit=>10})
   -> 0.3685s
.....

After that I removed the wiki_books folder, executed the " rake redmine:plugins:migrate RAILS_ENV=production" command and copied the wiki_books folder again in this plugin folder.

Then I started the migration again, but still no creation of the needed tables.

[root@redmine plugins]# rake redmine:plugins:migrate RAILS_ENV=production
(in /var/www/redmine)
Migrating issue_id (ISSUE-id)...
Migrating redmine_dmsf (DMSF)...
Migrating redmine_wiki_books (Redmine Wiki Books plugin)...
Migrating redmine_wiki_extensions (Redmine Wiki Extensions plugin)...


Did you try wiki_books with redmine 2.6.0?
Perhaps this could be the cause? What do you think?

**Comment by dedel1337** [comment]
directory redmine_wiki_books-master  changed to "redmine_wiki_books".

files in /redmine/plugins/redmine_wiki_books/db/migrate/ changed to
201_create_books.rb  
202_create_book_chapters.rb  
203_rename_tables.rb

then the migration is successful. 
There was an conflict with the name of the db/migrate files, because 001-003 already exists,.

With this redmine_wiki_books is also working on redmine 2.6
