### ISSUE TITLE
500 error in redmine 3.2.X

### ISSUE THREAD

**Issue by archonwang** [txinto/redmine_wiki_books#11]
when I edit the wiki book and click the [save] button, it occurs an error.

error log is 

> Started POST "/books/2/edit" for 192.168.60.239 at 2016-04-15 18:02:33 +0800
> Processing by BooksController#edit as HTML
>   Parameters: {"utf8"=>"✓", "authenticity_token"=>"VeE8iwQBH2k/rO6lPNN7NpgYByXSk8BAsf7MHcOWul8wqFTPnJAH8U1EeEEC3TGEJjYKic8swaRYSF3NcJuO2Q==", "book"=>{"title"=>"UTH_TestTeam Dairy Report 2016", "description"=>"<p>Test log</p>\r\n\r\n<h3>worklog</h3>\r\n\r\n<blockquote>\r\n<p>today's work</p>\r\n\r\n<ol>\r\n\t<li>&nbsp;</li>\r\n</ol>\r\n\r\n<p>nextday's work</p>\r\n\r\n<ol>\r\n\t<li>&nbsp;</li>\r\n</ol>\r\n</blockquote>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n"}, "commit"=>"save", "id"=>"2"}
>   Current user: admin (id=1)
> Completed 500 Internal Server Error in 12ms (ActiveRecord: 3.3ms)
> 
> ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
>   plugins/redmine_wiki_books/app/controllers/books_controller.rb:45:in `edit'
>   lib/redmine/sudo_mode.rb:63:in`sudo_mode'

**Comment by txinto** [comment]
Hello, have you used the 0.0.3 or the 0.0.5?
The 0.0.5 is needed for 3.x, it is not still in the master branch, it is in the rm3 branch.
It can be downloaded here: https://github.com/txinto/redmine_wiki_books/releases

If you are already using 0.0.5, then it is a real issue.

Best regards, and thank you for using the plugin.

**Comment by txinto** [comment]
Sorry, I found it.
I have fixed it and 0.0.6 will be available in a while.
Best regards!

**Comment by txinto** [comment]
Fixed in commit 83f730aeef1b478cf007eb466333c90e276ba76d

**Comment by archonwang** [comment]
Tested it OK!
Thanks~
And I used it in Redmine 3.2.X with Version 0.0.5.
